<script lang="ts">
	import { resolveAppPath, resolveAssetPath } from '$lib/utils/paths';
	import PageHeader from '$lib/components/PageHeader.svelte';
	import PageSection from '$lib/components/PageSection.svelte';

	import {
		aiGeneratedImages,
		aiEditedImages
	} from '$lib/data/ai-images';

	const generatedImages = aiGeneratedImages;
	const editedImages = aiEditedImages;
</script>

<svelte:head>
	<title>AI Transparency | D&D Portal</title>

	<meta
		name="description"
		content="Information about the use of artificial intelligence on D&D Portal, including a list of AI-generated and AI-edited images."
	/>
</svelte:head>

<PageHeader
	title="AI Transparency"
	description="Information about how artificial intelligence is used on D&D Portal and which images were generated or modified using AI."
	eyebrow="Website transparency"
/>

<PageSection title="Use of artificial intelligence">
	<p>
		D&D Portal uses artificial intelligence for a limited number of supporting
		visuals, including character concepts, class-card illustrations, campaign
		locations, non-player characters, monsters, and visual variations.
	</p>

	<p>
		These images are used to provide players with a quick visual impression of the
		content being described. They are not intended to replace official artwork,
		commissioned artwork, or the work of professional artists.
	</p>

	<p>
		AI-generated images on this website are not presented as original hand-drawn,
		painted, photographed, or manually illustrated works by Toon van Berkel.
	</p>
</PageSection>

<PageSection title="How AI images are used">
	<p>
		AI-generated and AI-assisted images may be used for:
	</p>

	<ul>
		<li>Class and subclass cards.</li>
		<li>Homebrew character concepts.</li>
		<li>Species and creature references.</li>
		<li>Campaign locations and environments.</li>
		<li>Non-player character portraits.</li>
		<li>Alternative character appearances.</li>
		<li>Background replacements and visual edits.</li>
		<li>Temporary illustrations while original artwork is unavailable.</li>
	</ul>

	<p>
		The presence of an AI-generated image does not mean that the related written
		content was also generated by AI.
	</p>
</PageSection>

<PageSection title="Image classifications">
	<p>
		Images on this page may use one of the following classifications:
	</p>

	<dl class="ai-definitions">
		<div>
			<dt>Generated</dt>
			<dd>
				The image was created primarily from a written description or prompt.
			</dd>
		</div>

		<div>
			<dt>AI-assisted edit</dt>
			<dd>
				An existing image was modified using an AI image-editing tool.
			</dd>
		</div>

		<div>
			<dt>Reference-based generation</dt>
			<dd>
				An existing image was used as a visual reference for composition,
				appearance, atmosphere, or subject matter.
			</dd>
		</div>

		<div>
			<dt>Background replacement</dt>
			<dd>
				The original subject was retained while the environment or background was
				replaced or significantly altered.
			</dd>
		</div>

		<div>
			<dt>Character variation</dt>
			<dd>
				An existing character concept was regenerated with changes such as gender,
				clothing, pose, species, or campaign form.
			</dd>
		</div>
	</dl>
</PageSection>

<PageSection title="AI-generated images">
	<p>
		The following images were generated primarily through an AI image-generation
		tool.
	</p>

	<div class="ai-gallery">
		{#each generatedImages as image}
			<article class="ai-card">
				<a
					class="ai-card__image-link"
					href={resolveAssetPath(image.image)}
					target="_blank"
					rel="noopener noreferrer"
					aria-label={`Open full image: ${image.title}`}
				>
					<img
						class="ai-card__image"
						src={resolveAssetPath(image.image)}
						alt={image.title}
						loading="lazy"
					/>
				</a>

				<div class="ai-card__content">
					<div class="ai-card__heading">
						<h3>{image.title}</h3>

						<span class="ai-card__type">
							{image.type}
						</span>
					</div>

					<p>{image.description}</p>

					<dl class="ai-card__details">
						{#if image.tool}
							<div>
								<dt>Tool</dt>
								<dd>{image.tool}</dd>
							</div>
						{/if}

						{#if image.reference}
							<div>
								<dt>Reference</dt>
								<dd>{image.reference}</dd>
							</div>
						{/if}

						{#if image.notes}
							<div>
								<dt>Notes</dt>
								<dd>{image.notes}</dd>
							</div>
						{/if}
					</dl>

					<div class="ai-card__links">
						<a href={resolveAssetPath(image.image)} target="_blank" rel="noopener noreferrer">
							View image
							<span aria-hidden="true">↗</span>
						</a>

						{#if image.page}
							<a href={resolveAppPath(image.page)}>
								View {image.pageLabel ?? 'related page'}
							</a>
						{/if}
					</div>
				</div>
			</article>
		{/each}
	</div>
</PageSection>

{#if editedImages.length > 0}
	<PageSection title="AI-assisted and edited images">
		<p>
			This section contains images that were based on an existing image or
			were modified using an AI-assisted editing process.
		</p>

		{#if editedImages.length > 0}
			<div class="ai-gallery">
				{#each editedImages as image}
					<article class="ai-card">
						<a
							class="ai-card__image-link"
							href={resolveAssetPath(image.image)}
							target="_blank"
							rel="noopener noreferrer"
							aria-label={`Open full image: ${image.title}`}
						>
							<img
								class="ai-card__image"
								src={resolveAssetPath(image.image)}
								alt={image.title}
								loading="lazy"
							/>
						</a>

						<div class="ai-card__content">
							<div class="ai-card__heading">
								<h3>{image.title}</h3>

								<span class="ai-card__type">
									{image.type}
								</span>
							</div>

							<p>{image.description}</p>

							<dl class="ai-card__details">
								{#if image.tool}
									<div>
										<dt>Tool</dt>
										<dd>{image.tool}</dd>
									</div>
								{/if}

								{#if image.reference}
									<div>
										<dt>Reference</dt>
										<dd>{image.reference}</dd>
									</div>
								{/if}

								{#if image.notes}
									<div>
										<dt>Notes</dt>
										<dd>{image.notes}</dd>
									</div>
								{/if}
							</dl>

							<div class="ai-card__links">
								<a
									href={resolveAssetPath(image.image)}
									target="_blank"
									rel="noopener noreferrer"
								>
									View image
									<span aria-hidden="true">↗</span>
								</a>

								{#if image.page}
									<a href={resolveAppPath(image.page)}>
										View {image.pageLabel ?? 'related page'}
									</a>
								{/if}
							</div>
						</div>
					</article>
				{/each}
			</div>
		{:else}
			<div class="ai-empty-state">
				<div class="ai-empty-state__icon" aria-hidden="true">
					<svg viewBox="0 0 24 24">
						<path d="M12 3v2" />
						<path d="M12 19v2" />
						<path d="m4.22 4.22 1.42 1.42" />
						<path d="m18.36 18.36 1.42 1.42" />
						<path d="M3 12h2" />
						<path d="M19 12h2" />
						<path d="m4.22 19.78 1.42-1.42" />
						<path d="m18.36 5.64 1.42-1.42" />
						<circle cx="12" cy="12" r="4" />
					</svg>
				</div>

				<div>
					<h3>No AI-assisted edits are currently registered</h3>

					<p>
						At this time, D&D Portal does not use images that were
						created by modifying an existing image with an AI editing
						tool.
					</p>

					<p>
						If AI-assisted edits are added in the future, they will be
						registered and displayed in this section.
					</p>
				</div>
			</div>
		{/if}
	</PageSection>
{/if}

<PageSection title="Official and third-party material">
	<p>
		AI-generated images listed on this page are not official Dungeons & Dragons
		artwork and should not be interpreted as official representations of a class,
		species, monster, character, location, or setting.
	</p>

	<p>
		Dungeons & Dragons, D&D, Wizards of the Coast, and related properties belong to
		Wizards of the Coast LLC and their respective rights holders.
	</p>

	<p>
		Where an AI image was based on a user-provided or third-party reference image,
		that reference does not become the property of D&D Portal. Rights in the original
		reference remain with the relevant creator or rights holder.
	</p>
</PageSection>

<PageSection title="Corrections and removal requests">
	<p>
		If you believe that an image has been labelled incorrectly, is missing relevant
		information, resembles protected material too closely, or should be removed,
		please contact:
	</p>

	<p>
		<a href="mailto:toonvanberkel.public@gmail.com">
			toonvanberkel.public@gmail.com
		</a>
	</p>

	<p>
		Please include the page URL, the name of the image, a description of the issue,
		and any relevant ownership or source information.
	</p>
</PageSection>

<PageSection title="Related information">
	<ul>
		<li>
			<a href={resolveAppPath('/credits')}>Credits and acknowledgements</a>
		</li>
		<li>
			<a href={resolveAppPath('/sources')}>Sources and references</a>
		</li>
		<li>
			<a href={resolveAppPath('/legal')}>Legal notice</a>
		</li>
		<li>
			<a href={resolveAppPath('/privacy')}>Privacy notice</a>
		</li>
	</ul>
</PageSection>

<style lang="scss">
	@use './AITransparency.scss';
</style>
